version: '3.3'
services:
  mediamtx:
    container_name: rtsp
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_RTSPADDRESS=0.0.0.0:554
      - MTX_LOGLEVEL=error
      - MTX_API=yes
      - MTX_APIADDRESS=0.0.0.0:9997
      - MTX_PATHS_TIMER_RUNONDEMAND=ffmpeg -hide_banner -loglevel error -stream_loop -1 -re -i timer.mp4 -c:v libx264 -preset ultrafast -tune zerolatency -an -f rtsp rtsp://0.0.0.0/timer
      - MTX_PATHS_TIMER_RUNONDEMANDRESTART=yes
      - MTX_PATHS_RESTREAM_RUNONDEMAND=ffmpeg -hide_banner -loglevel error -i rtsp://0.0.0.0/timer -c copy -f rtsp rtsp://0.0.0.0/restream
      - MTX_PATHS_RESTREAM_RUNONDEMANDRESTART=yes
    image: bluenviron/mediamtx:latest-ffmpeg
    ports:
      - '554:554'
      - '9997:9997'
    # network_mode: host
    restart: always
    volumes:
      - ./:/video
    working_dir: /video
